### ISSUE TITLE
Limit holding jobs to certain branchs

### ISSUE THREAD

**Issue by jeffpearce** [jenkinsci/working-hours-plugin#7]
It would be nice to be able to limit holding jobs to certain branches. One use case for this plugin is to prevent deployments, but those typically are scoped to certain branches. It would be nice to allow branches that don't deploy (such as PRs) to proceed.

One idea would be to add some properties, e.g.

 `enforceBuildSchedule(branches: ['master', 'prod', 'test'])`

But other solutions are welcome

**Comment by amedee** [comment]
Would something like this work? Have not tried it myself.

```
pipeline {
  agent any

  stages {
    stage('Deploy') {
      options {
        enforceBuildSchedule()
      }
      when {
        anyOf {
          branch "staging"
          branch "production"
        }
      }
      steps {
        echo 'Deploy to staging or production during working hours'
      }
    }
  }
}
```

Coming to think of it, you could just not use this plugin at all and put something scripted in the `when`-construct. But this plugin makes it a lot more convenient.

**Comment by jeffpearce** [comment]
I don't think that works. Unless the plugin evaluated the entire script, the job would start running before that when clause would be evaluated, and by then it's too late - it needs to actually block the job from leaving the queue. Worth thinkin about though
